defaults:
  header: "/* \n
          * Printed Wood Arm Joints\n
          * \n
          * Copyright 2017 Mitsuaki Fujii - silvershell100@gmail.com\n
          * This program is free software: you can redistribute it and/or modify\n
          * it under the terms of the GNU General Public License as published by\n
          * the Free Software Foundation, either version 3 of the License, or\n
          * (at your option) any later version.\n
          *\n
          * This program is distributed in the hope that it will be useful,\n
          * but WITHOUT ANY WARRANTY; without even the implied warranty of\n
          * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n
          * GNU General Public License for more details.\n
          *\n
          * See <http://www.gnu.org/licenses/>.\n
          */"
  footer: ""
  include: 
  - ./lib/util.scad
models:

# - dest: forEdit
#   module: printed-wood-arm-joints
#   func: forEdit

# - dest: preview1
#   module: printed-wood-arm-joints
#   func: preview1

# - dest: preview2
#   module: printed-wood-arm-joints
#   func: preview2

# - dest: preview3
#   module: printed-wood-arm-joints
#   func: preview3

- dest: joint1
  module: printed-wood-arm-joints
  func: joint1

- dest: joint2
  module: printed-wood-arm-joints
  func: joint2

- dest: joint3
  module: printed-wood-arm-joints
  func: joint3

- dest: joint4
  module: printed-wood-arm-joints
  func: joint4

- dest: joint5
  module: printed-wood-arm-joints
  func: joint5

- dest: spacer1
  module: printed-wood-arm-joints
  func: spacer1

- dest: spacer2
  module: printed-wood-arm-joints
  func: spacer2


- dest: nutHolder
  module: printed-wood-arm-joints
  func: nutHolder

- dest: boltHandle1
  module: printed-wood-arm-joints
  func: boltHandle1

- dest: boltHandle2
  module: printed-wood-arm-joints
  func: boltHandle2

- dest: mounter
  module: printed-wood-arm-joints
  func: mounter

- dest: attachmentMilkBottle
  module: printed-wood-arm-joints
  func: attachmentMilkBottle

- dest: attachmentRotate
  module: printed-wood-arm-joints
  func: attachmentRotate

- dest: smartPhoneGrip1
  module: printed-wood-arm-joints
  func: smartPhoneGrip1

- dest: smartPhoneGrip2
  module: printed-wood-arm-joints
  func: smartPhoneGrip2

